### PR TITLE
Corrected image visibility issue - tech-stack page

### PR DESCRIPTION
**Pull request by jobyko**

### CODE REVIEW

**Comment by jobyko** [comment]
@asa1997 
Please have a look on this.

change:
corrected oss tracker image visibility issue under 'tech-stack' page (fixed by correcting the path)

**Review by asa1997 — APPROVED** [review]
@jobyko @panickervinod LGTM

**Comment by jobyko** [comment]
Updated the links of "Our OSS Project " too with this pull request. 
@asa1997 
Please have a look.

**Comment by panickervinod** [comment]
Merging this one however link to Readme.md after making necessary changes in the respective project Readme.md files.

**Pull request merged**
